### ISSUE TITLE
We can't find the internet error

### ISSUE THREAD

**Issue by jpcapone** [sergiotapia/magnetissimo#149]
Fresh docker deployment and I am able to connect to the app but I get this error
![image](https://user-images.githubusercontent.com/47680328/231931263-e6fac6c7-4f5f-4ca9-9ea2-5988c64ddd5e.png)

any suggestions?

**Comment by sergiotapia** [comment]
I know what this is @jpcapone - There's another environment variable that you need to set called `PHX_HOST` so the websocket can connect.

This is so that when you deploy any Phoenix app to prod, you can only connect to your backend from mydomain.com.

In this case you're just hitting localhost:4000 right? I just pushed a change that may fix this - could you pull it down and give it a try? Thanks for helping me figure this out.

**Comment by jpcapone** [comment]
Thanks for getting back to me.  I killed the container and deleted the image and forced a redownload and the issue remains.  I am sure you already know what the log looks like but below i have added a snipped
`03:34:49.210 [error] Could not check origin for Phoenix.Socket transport.
Origin of the request: http://10.229.181.90:4000
This happens when you are attempting a socket connection to
a different host than the one configured in your config/
files. For example, in development the host is configured
to "localhost" but you may be trying to access it from
"127.0.0.1". To fix this issue, you may either:
  1. update [url: [host: ...]] to your actual host in the
     config file for your current environment (recommended)
  2. pass the :check_origin option when configuring your
     endpoint or when configuring the transport in your
     UserSocket module, explicitly outlining which origins
     are allowed:
        check_origin: ["https://example.com",
                       "//another.com:888", "//other.com"]`

**Comment by askiiart** [comment]
How do I allow connections to any address? I tried `- PHX_HOST=0.0.0.0`, but that didn't work.

**Comment by sergiotapia** [comment]
Asking for some help in the ElixirForums here - https://elixirforum.com/t/could-not-check-origin-for-phoenix-socket-transport-in-prod-running-on-docker/55269

I don't know how to fix this

**Comment by afarazit** [comment]
@askiiart try - PHX_HOST=magnetissimo.domain.tld, replace magnetissimo.domain.tld with your domain

**Comment by jpcapone** [comment]
> @askiiart try - PHX_HOST=magnetissimo.domain.tld, replace magnetissimo.domain.tld with your domain

would this work for my issue as well?  I assume i should have a dns record that resolves the domain name?

**Comment by afarazit** [comment]
@jpcapone you can give it a try, also if you are using Nginx Proxy Manager be sure to enable Websockets support

**Comment by jpcapone** [comment]
> magnetissimo

I am not using any proxying within my home network       
added this line to the docker compose file
`PHX_HOST=magnetissimo.blahblah.bla`
still getting
![image](https://user-images.githubusercontent.com/47680328/232174142-73e610e5-824f-41fa-ba5c-d1825f1edda7.png)

I created and confirmed resolution to the PHX_HOST entry.  Any other suggestions.

**Comment by askiiart** [comment]
@jpcapone

Use `PHX_HOST=<IP_ADDRESS_HERE>`, for example `PHX_HOST=192.168.1.23`

**Comment by jpcapone** [comment]
That did it for me.  I am in!

**Comment by sergiotapia** [comment]
Fantastic!

**Comment by Ethergy** [comment]
> @jpcapone
> 
> Use `PHX_HOST=<IP_ADDRESS_HERE>`, for example `PHX_HOST=192.168.1.23`

I have done this but am still experiencing the issue

**Comment by askiiart** [comment]
@Ethergy Could you please provide logs?

**Comment by Ethergy** [comment]
> @Ethergy Could you please provide logs?
[_magnetissimo_logs.txt](https://github.com/sergiotapia/magnetissimo/files/11240457/_magnetissimo_logs.txt)
Looks like it's whatever is going on in #161 actually
